[project]
name = "atari-cr"
version = "0.1.0"
description = "Playing atari with human-plausible vision"
authors = [
    { name = "Niko Konzack", email = "niko-konzack@t-online.de" }
]
license = { text = "MIT" }
readme = "README.md"
requires-python = ">=3.9,<3.11"
dependencies = [
    "active-gym @ git+https://github.com/elicassion/active-gym.git#main",
    # sudo apt install libx11-dev libglew-dev patchelf
    # python -m atari_py.import_roms .ROMS
    "stable-baselines3[extra]",
    "cython<3",
]
classifiers = [
    "Private :: Do Not Upload"
]

[project.urls] 
Repository = "https://github.com/Niko32/sugarl"

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"